merging align_se and pe

diff --git a/scripts/align_se b/scripts/align_se
--- a/scripts/align_se
+++ b/scripts/align_se
@@ -1,12 +1,28 @@
 #!/bin/bash
 
-fastq1=$1
-index=$2
-outdir=$3
-prefix=$4
-nThreads=$5
-
-
-# run bwa
-bwa mem -t $nThreads -v 2 $index $fastq1 | samtools view -Shb - > $prefix.bam
+INPUT=$1
+INDEXFILE=$2
+OUTDIR=$3
+PREFIX=$4
+NTHREADS=$3
+  
+   ISPAIRED=$(head -n 8 $INPUT | paste - - - - | awk '{print $1}' | uniq -c | awk '{print $1}' | head -n 1)
+   if [[ $ISPAIRED -eq 2 ]]; then
+     PAIRARG="-p"
+     >&2 echo "fastq is interleaved, treating as paired-end"
+   else
+     PAIRARG=""
+     >&2 echo "fastq is not interleaved, treating as single-end"
+   fi
+   
+   # check if file exists
+   if [[ ! -f $INPUT ]]; then echo "fastq file \"$INPUT\" not found"; exit 1; fi
+   # check input is a fastq
+   if [[ $INPUT != *.fastq ]] && [[ $INPUT != *.fq ]]; then echo "input is not an uncompressed fastq"; exit 1; fi
+   
+   OUTPUT=$OUTDIR/$PREFIX.bam
+   LOGFILE=${OUTPUT}.log
+   
+   bwa mem $PAIRARG -v 2 -t $NTHREADS $INDEXFILE $INPUT | samtools view -Shb - > $OUTPUT
+   echo $OUTPUT
 
