rewrote the other steps

diff --git a/scripts/count b/scripts/count
--- a/scripts/count
+++ b/scripts/count
@@ -1,36 +1,12 @@
 #!/usr/bin/env bash
+INPUT=$1
+OUTPREFIX=$2
+WINSIZE=$3
+MINSIZE=$4
 
-usage() {
-  >&2 echo "Usage: $(basename $0) [-t threads ] -w windows.bed bed1 [bed2 ... bedN ]"
-  >&2 echo ""
-  exit 1
-}
-
-while getopts ":t:w:m:" opt; do
-  case $opt in
-  m)
-    MINSIZE=$OPTARG
-   ;;
-  t)
-    NTHREADS=$OPTARG
-   ;;
-  w)
-    WINSIZE=$OPTARG
-   ;;
-  \?)
-   >&2 echo "Invalid option: -$OPTARG"
-   usage
-   ;;
-  [?])
-   usage
-   ;;
-  :)
-   >&2 echo "Option -$OPTARG requires an argument."
-   >&2 echo ""
-   usage
-   ;;
-  esac
-done
+if [ -z $OUTPREFIX ]; then
+  OUTPREFIX=out
+fi
 
 if [ -z $WINSIZE ]; then
   WINSIZE=5000
@@ -40,47 +16,16 @@ if [ -z $MINSIZE ]; then
   MINSIZE=10000000
 fi
 
-if [ -z $NTHREADS ]; then
-  if [ -z $NUMTHREADS ]; then
-    NTHREADS=1
-  else
-    NTHREADS=$NUMTHREADS
-  fi
-fi
-
-shift $((OPTIND-1))
-
-if [[ -z $@ ]]; then
-  INPUT=$(cat /dev/stdin)
-else
-  INPUT=$@
-fi
-
-count(){
-  INPUT=$1
-  WINSIZE=$2
-  MINSIZE=$3
+# check if file exists
+if [[ ! -f $INPUT ]]; then >&2 echo "file \"$INPUT\" not found"; exit 1; fi
   
-  # check if file exists
-  if [[ ! -f $INPUT ]]; then >&2 echo "file \"$INPUT\" not found"; exit 1; fi
+BASE=$OUTPREFIX
+OUTPUT=${BASE}_w${WINSIZE}.bg
   
-  # check input is a bed
-  if [[ $INPUT != *.bam ]]; then >&2 echo "input is not a bam file"; exit 1; fi
+SCALE=$(echo "1000000/$(samtools view -c $INPUT)" | bc -l)
   
-  BASE="$(basename $INPUT | sed 's/\.bam$//g')"
-  OUTPUT=${BASE}_w${WINSIZE}.bg
-  
-  SCALE=$(echo "1000000/$(samtools view -c $INPUT)" | bc -l)
-  
-  samtools view -H $INPUT | grep "^@SQ" | tr ':' '\t' | cut -f 3,5 | \
-  awk -v minsize=$MINSIZE '$2>minsize' OFS='\t' | \
-  bedtools makewindows -w $WINSIZE -g /dev/stdin | \
-  bedtools coverage -counts -sorted -c -a stdin -b $INPUT | \
-  awk -v scale=$SCALE '{print $1,$2,$3,$4*1000*(scale/($3-$2)) }' OFS='\t' > $OUTPUT
-  
-  echo $OUTPUT
-}
-
-export -f count
-
-parallel --no-notice -k -j $NTHREADS "count {} $WINSIZE $MINSIZE" ::: $INPUT
+samtools view -H $INPUT | grep "^@SQ" | tr ':' '\t' | cut -f 3,5 | \
+awk -v minsize=$MINSIZE '$2>minsize' OFS='\t' | \
+bedtools makewindows -w $WINSIZE -g /dev/stdin | \
+bedtools coverage -counts -sorted -c -a stdin -b $INPUT | \
+awk -v scale=$SCALE '{print $1,$2,$3,$4*1000*(scale/($3-$2)) }' OFS='\t' > $OUTPUT
diff --git a/scripts/dedup b/scripts/dedup
--- a/scripts/dedup
+++ b/scripts/dedup
@@ -1,72 +1,20 @@
 #!/usr/bin/env bash
-
-usage() {
-  echo "Usage: $(basename $0) [-t threads ] fastq1 [fastq2 ... fastqN ]" 1>&2
-  echo "" 1>&2
-  exit 1
-}
-
-while getopts ":t:" opt; do
-  case $opt in
-  t)
-    NTHREADS=$OPTARG
-   ;;
-  \?)
-   echo "Invalid option: -$OPTARG" >&2
-   usage
-   ;;
-  [?])
-   usage
-   ;;
-  :)
-   echo "Option -$OPTARG requires an argument." >&2
-   echo "" >&2
-   usage
-   ;;
-  esac
-done
-
-if [ -z $NTHREADS ]; then
-  if [ -z $NUMTHREADS ]; then
-    NTHREADS=1
-  else
-    NTHREADS=$NUMTHREADS
-  fi
-fi
-
-shift $((OPTIND-1))
-
-if [[ -z $@ ]]; then
-  INPUT=$(cat /dev/stdin)
+INPUT=$1
+OUTPREFIX=$2
+  
+# check if file exists
+if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi
+  
+UCOUNT=$(samtools view $INPUT | cut -f 1 | head -n 1000 | sort | uniq | wc -l)
+  
+if [[ UCOUNT -lt 1000 ]]; then
+  PAIRARG=""
 else
-  INPUT=$@
-fi
-
-dedup(){
-  INPUT=$1
+  PAIRARG="-s"
+fi 
   
-  # check if file exists
-  if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi
+BASE=$OUTPREFIX
+OUTPUT=${BASE}_rmdup.bam
+LOGFILE=${BASE}_rmdup.bam.log
   
-  # check input is a fastq
-  if [[ $INPUT != *.bam ]]; then echo "input is not a bam file"; exit 1; fi
-  
-  UCOUNT=$(samtools view $INPUT | cut -f 1 | head -n 1000 | sort | uniq | wc -l)
-  
-  if [[ UCOUNT -lt 1000 ]]; then
-    PAIRARG=""
-  else
-    PAIRARG="-s"
-  fi 
-  
-  BASE="$(basename $INPUT | sed 's/\.bam$//g')"
-  OUTPUT=${BASE}_rmdup.bam
-  LOGFILE=${BASE}_rmdup.bam.log
-  
-  samtools rmdup $PAIRARG $INPUT $OUTPUT 2> $LOGFILE
-  echo $OUTPUT
-}
-
-export -f dedup
-
-parallel --no-notice -k -j $NTHREADS "dedup {}" ::: $INPUT
+samtools rmdup $PAIRARG $INPUT $OUTPUT 2> $LOGFILE
diff --git a/scripts/filter b/scripts/filter
--- a/scripts/filter
+++ b/scripts/filter
@@ -1,75 +1,27 @@
 #!/usr/bin/env bash
+INPUT=$1  # .bg
+OUTPREFIX=$2
+MINRPKM=$3
 
-usage() {
-  echo "Usage: $(basename $0) [-m minRPKM -t threads ] bedGraph1 [bedGraph2 bedGraphN ]" 1>&2
-  echo "" 1>&2
-  exit 1
-}
-
-while getopts ":m:t:" opt; do
-  case $opt in
-  t)
-    NUMTHREADS=$OPTARG
-   ;;
-  m)
-    MINRPKM=$OPTARG
-   ;;
-  \?)
-   echo "Invalid option: -$OPTARG" >&2
-   usage
-   ;;
-  [?])
-   usage
-   ;;
-  :)
-   echo "Option -$OPTARG requires an argument." >&2
-   echo "" >&2
-   usage
-   ;;
-  esac
-done
-
-if [ -z $NTHREADS ]; then
-  if [ -z $NUMTHREADS ]; then
-    NTHREADS=1
-  else
-    NTHREADS=$NUMTHREADS
-  fi
+if [ -z $OUTPREFIX ]; then
+  OUTPREFIX=out
 fi
 
 if [ -z $MINRPKM ]; then
   MINRPKM=0.1
 fi
 
-shift $((OPTIND-1))
-
-if [[ -z $@ ]]; then
-  INPUT=$(cat /dev/stdin)
-else
-  INPUT=$@
-fi
-
-for i in $INPUT; do
-  if [[ ! -f $i ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi
-  if [[ $i != *.bg ]]; then >&2 echo "file \"$i\" is not a bedGraph file"; exit 1; fi
-done
+if [[ ! -f $INPUT ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi
 
 paste $INPUT | awk -v minrpkm=$MINRPKM \
   '{for(i=4;i<=NF;i+=4){scoresum+=$i}; if((scoresum/(NF/4))>=minrpkm){print $1,$2,$3};scoresum=0}' \
 OFS='\t' > filtered.bed
 
-intersect(){
-  BG=$1
-  FW=$2
+BG=$INPUT
+FW=filtered.bed
   
-  BASE="$(basename $BG | sed 's/\.bg$//g')"
-  OUTPUT="${BASE}_filtered.bg"
+BASE=$OUTPREFIX
+OUTPUT="${BASE}_filtered.bg"
   
-  bedtools intersect -sorted -u -a $BG -b $FW > $OUTPUT
-  
-  echo $OUTPUT
-}
-
-export -f intersect
-
-parallel --no-notice -k -j $NTHREADS "intersect {} filtered.bed" ::: $INPUT
+bedtools intersect -sorted -u -a $BG -b $FW > $OUTPUT
+ 
diff --git a/scripts/log2ratio b/scripts/log2ratio
--- a/scripts/log2ratio
+++ b/scripts/log2ratio
@@ -1,80 +1,22 @@
 #!/usr/bin/env bash
+EBG=$1
+LBG=$2
+OUTPREFIX=$3
 
-usage() {
-  echo "Usage: $(basename $0) [-t threads ] sample1_early.bg [sample2_early.bg sampleN_early.bg ] sample1_late.bg [sample2_late.bg sampleN_late.bg]" 1>&2
-  echo "" 1>&2
-  exit 1
-}
+# check if file exists
+if [[ ! -f $EBG ]]; then echo "file \"$EBG\" not found"; exit 1; fi
+if [[ ! -f $LBG ]]; then echo "file \"$LBG\" not found"; exit 1; fi
 
-while getopts ":t:" opt; do
-  case $opt in
-  t)
-    NTHREADS=$OPTARG
-   ;;
-  \?)
-   echo "Invalid option: -$OPTARG" >&2
-   usage
-   ;;
-  [?])
-   usage
-   ;;
-  :)
-   echo "Option -$OPTARG requires an argument." >&2
-   echo "" >&2
-   usage
-   ;;
-  esac
-done
+# check input is a fastq
+if [[ $EBG != *.bg ]]; then echo "input is not a bedGraph file"; exit 1; fi
+if [[ $LBG != *.bg ]]; then echo "input is not a bedGraph file"; exit 1; fi
 
-if [ -z $NTHREADS ]; then
-  if [ -z $NUMTHREADS ]; then
-    NTHREADS=1
-  else
-    NTHREADS=$NUMTHREADS
-  fi
-fi
-
-shift $((OPTIND-1))
-
-if [[ -z $@ ]]; then
-  INPUT=$(cat /dev/stdin)
-else
-  INPUT=$@
-fi
-
-NUMSAMPLES=$(echo $INPUT | tr ' ' '\n' | paste - - | wc -l)
-EBGS=$(echo $INPUT | tr ' ' '\n' | head -n $NUMSAMPLES)
-LBGS=$(echo $INPUT | tr ' ' '\n' | tail -n $NUMSAMPLES)
-
-l2r(){
-  EBG=$1
-  LBG=$2
-  # check if file exists
-  if [[ ! -f $EBG ]]; then echo "file \"$EBG\" not found"; exit 1; fi
-  if [[ ! -f $LBG ]]; then echo "file \"$LBG\" not found"; exit 1; fi
-  
-  # check input is a fastq
-  if [[ $EBG != *.bg ]]; then echo "input is not a bedGraph file"; exit 1; fi
-  if [[ $LBG != *.bg ]]; then echo "input is not a bedGraph file"; exit 1; fi
-  
-  EMIN=$(cut -f 4 $EBG | sort | uniq -c | awk '{print $2-a;a=$2}' | sort | uniq -c | awk '{print $1,$2}' | sort -k1,1nr | head -n 1 | cut -d' ' -f 2)
-  LMIN=$(cut -f 4 $LBG | sort | uniq -c | awk '{print $2-a;a=$2}' | sort | uniq -c | awk '{print $1,$2}' | sort -k1,1nr | head -n 1 | cut -d' ' -f 2)
-  
-  OUTPUT="$(basename $EBG | sed 's/\.bg$/_l2r\.bg/g')"
-  LOGFILE=${OUTPUT}.log
-  
-  paste $EBG $LBG | awk -v emin=$EMIN -v lmin=$LMIN '{print $1,$2,$3,log(($4+emin)/($8+lmin))/log(2)}' OFS='\t' > $OUTPUT
-  
-  echo $OUTPUT
-}
-
-export -f l2r
-
-# using 1 thread until I figure out how to get equivalent function of --link with older versions of parallel
-parallel --no-notice -k -j 1 l2r ::: $EBGS ::: $LBGS
+EMIN=$(cut -f 4 $EBG | sort | uniq -c | awk '{print $2-a;a=$2}' | sort | uniq -c | awk '{print $1,$2}' | sort -k1,1nr | head -n 1 | cut -d' ' -f 2)
+LMIN=$(cut -f 4 $LBG | sort | uniq -c | awk '{print $2-a;a=$2}' | sort | uniq -c | awk '{print $1,$2}' | sort -k1,1nr | head -n 1 | cut -d' ' -f 2)
 
 
-# BGLINES=$(wc -l $EARLYBG | cut -d" " -f 1)
-# RTLINES=$(wc -l ${PREFIX}.bg | cut -d" " -f 1)
-# PCTZEROES=$(echo "${RTLINES}/${BGLINES}" | bc -l)
-# echo "${PCTZEROES} of the ${BGLINES} windows have 0 reads in either fraction" > ${PREFIX}.bg.log
+OUTPUT=$OUTPREFIX.l2r.out  ## is this bg?
+LOGFILE=${OUTPUT}.log
+
+paste $EBG $LBG | awk -v emin=$EMIN -v lmin=$LMIN '{print $1,$2,$3,log(($4+emin)/($8+lmin))/log(2)}' OFS='\t' > $OUTPUT
+
