Update normalize

diff --git a/scripts/normalize b/scripts/normalize
--- a/scripts/normalize
+++ b/scripts/normalize
@@ -1,20 +1,26 @@
 #!/usr/bin/env bash
 INPUT=$1
-OUTPREFIX=$2  # optional
-REFERENCE=$3  # optional
+OUTDIR=$2  # default "."
+OUTPREFIX=$3  # default "out"
+REFERENCE=$4  # optional bedgraph (.bg) file
+
+# check input file exists
+if [[ ! -f $INPUT ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi
+
+# default options
+if [ -z $OUTDIR ]; then
+  OUTDIR=.
+fi
 
 if [ -z $OUTPREFIX ]; then
   OUTPREFIX=out
 fi
 
-for i in $INPUT; do
-  if [[ ! -f $i ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi
-done
 
 iqrn(){
   BG=$1
-  BASE=$OUTPREFIX
-  OUTPUT="${BASE}_inorm.bg"
+  BASE=$OUTDIR/$OUTPREFIX
+  OUTPUT="${BASE}.inorm.bg"
   
   NUMLINES=$(cat $BG | wc -l)
   Q1=$(echo $NUMLINES/4 | bc)
@@ -33,8 +39,8 @@ normalize(){
   BG=$1
   RF=$2
   
-  BASE=$OUTPREFIX
-  OUTPUT="${BASE}_qnorm.bg"
+  BASE=$OUTDIR/$OUTPREFIX
+  OUTPUT="${BASE}.qnorm.bg"
   BGLINES=$(cat $BG | wc -l)
   RFLINES=$(cat $RF | wc -l)
   TMPREFN="$(mktemp).bg"
@@ -59,11 +65,6 @@ if [[ ! -f $REFERENCE ]]; then
   tmprefi="$(mktemp).bg"
   cat $INPUTI > $tmprefi
   REFERENCE=$tmprefi
-else
-  if [[ $REFERENCE != *.bg ]]; then
-    >&2 echo "file \"$REFERENCE\" is not a bedGraph file"
-    exit 1
-  fi
 fi
 
 normalize $INPUT $REFERENCE
